name: release
# generating and testing package artefacts from the main branch

on:
  push:
    branches:
      - main
      - update-docker-release
    tags:
      - '*'

jobs:
  release_tag_docker:
    if: github.repository == 'Project-MONAI/MONAI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: build with the tag
        shell: bash
        run: |
          RELEASE_VERSION=1.1.0rc4
          # get tag info for versioning
          mv _version.py monai/
          # version checks
          target=" \"version\": \"$RELEASE_VERSION\""
          local=`grep "\"version\"" monai/_version.py`
          echo "$target"
          echo "$local"
          if [[ "$local" == "$target" ]]; then
            echo "matched version string"
          else
            echo "unmatched version string, please check the tagging branch."
            exit 1
          fi
          # remove flake package as it is not needed on hub.docker.com
          sed -i '/flake/d' requirements-dev.txt
          docker build -t projectmonai/monai:"$RELEASE_VERSION" -f Dockerfile .
          # distribute with a tag to hub.docker.com
          echo "${{ secrets.DOCKER_PW }}" | docker login -u projectmonai --password-stdin
          docker push projectmonai/monai:"$RELEASE_VERSION"
          docker logout
